export interface VideoInfo {
  id: string;
  title: string;
  description: string;
  channel: string;
  duration: string;
  publishedAt: string;
  viewCount: string;
  thumbnail: string;
  language?: string;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  kind: string;
}

export interface CaptionsList {
  videoId: string;
  availableCaptions: CaptionTrack[];
  totalCount: number;
}

export interface CaptionSegment {
  start: number;
  duration: number;
  text: string;
}

export interface CaptionsData {
  videoId: string;
  language: string;
  format: 'raw' | 'srt' | 'vtt';
  isAutoGenerated: boolean;
  segments: CaptionSegment[];
  formattedContent?: string;
}

export interface SearchResult {
  videoId: string;
  title: string;
  channel: string;
  duration: string;
  thumbnail: string;
  availableCaptions: CaptionTrack[];
}

export interface SearchResponse {
  query: string;
  results: SearchResult[];
  totalCount: number;
}

// 新しいトランスクリプト関連の型定義
export interface RawTranscriptSegment {
  type: string;
  start_ms: string;
  end_ms: string;
  snippet: {
    text: string;
  };
}

export interface RawTranscript {
  transcript: {
    content: {
      body: {
        initial_segments: RawTranscriptSegment[];
      };
    };
  };
}


export interface FormattedTranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface FormattedTranscript {
  segments: FormattedTranscriptSegment[];
}
